services:
  - type: web
    name: mehrchain-api
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npx prisma generate --schema=apps/mehrchain-backend/prisma/schema.prisma && npx prisma db push --schema=apps/mehrchain-backend/prisma/schema.prisma --accept-data-loss && NX_DAEMON=false npx nx build mehrchain-backend
    startCommand: node dist/apps/mehrchain-backend/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
